/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitasRouteImport } from './routes/visitas'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RecordatoriosRouteImport } from './routes/recordatorios'
import { Route as PerfilesRouteImport } from './routes/perfiles'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as MaterialRouteImport } from './routes/material'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as InformesRouteImport } from './routes/informes'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as FacturasRouteImport } from './routes/facturas'
import { Route as ConsumoRouteImport } from './routes/consumo'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const VisitasRoute = VisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordatoriosRoute = RecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilesRoute = PerfilesRouteImport.update({
  id: '/perfiles',
  path: '/perfiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRoute = MaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesRoute = InformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturasRoute = FacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumoRoute = ConsumoRouteImport.update({
  id: '/consumo',
  path: '/consumo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/consumo': typeof ConsumoRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/informes': typeof InformesRoute
  '/inventario': typeof InventarioRoute
  '/material': typeof MaterialRoute
  '/pacientes': typeof PacientesRoute
  '/perfiles': typeof PerfilesRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/consumo': typeof ConsumoRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/informes': typeof InformesRoute
  '/inventario': typeof InventarioRoute
  '/material': typeof MaterialRoute
  '/pacientes': typeof PacientesRoute
  '/perfiles': typeof PerfilesRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/consumo': typeof ConsumoRoute
  '/facturas': typeof FacturasRoute
  '/gastos': typeof GastosRoute
  '/informes': typeof InformesRoute
  '/inventario': typeof InventarioRoute
  '/material': typeof MaterialRoute
  '/pacientes': typeof PacientesRoute
  '/perfiles': typeof PerfilesRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/consumo'
    | '/facturas'
    | '/gastos'
    | '/informes'
    | '/inventario'
    | '/material'
    | '/pacientes'
    | '/perfiles'
    | '/recordatorios'
    | '/usuarios'
    | '/visitas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/consumo'
    | '/facturas'
    | '/gastos'
    | '/informes'
    | '/inventario'
    | '/material'
    | '/pacientes'
    | '/perfiles'
    | '/recordatorios'
    | '/usuarios'
    | '/visitas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracion'
    | '/consumo'
    | '/facturas'
    | '/gastos'
    | '/informes'
    | '/inventario'
    | '/material'
    | '/pacientes'
    | '/perfiles'
    | '/recordatorios'
    | '/usuarios'
    | '/visitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ConsumoRoute: typeof ConsumoRoute
  FacturasRoute: typeof FacturasRoute
  GastosRoute: typeof GastosRoute
  InformesRoute: typeof InformesRoute
  InventarioRoute: typeof InventarioRoute
  MaterialRoute: typeof MaterialRoute
  PacientesRoute: typeof PacientesRoute
  PerfilesRoute: typeof PerfilesRoute
  RecordatoriosRoute: typeof RecordatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
  VisitasRoute: typeof VisitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitas': {
      id: '/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof VisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordatorios': {
      id: '/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof RecordatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfiles': {
      id: '/perfiles'
      path: '/perfiles'
      fullPath: '/perfiles'
      preLoaderRoute: typeof PerfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material': {
      id: '/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof MaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes': {
      id: '/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof InformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturas': {
      id: '/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof FacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumo': {
      id: '/consumo'
      path: '/consumo'
      fullPath: '/consumo'
      preLoaderRoute: typeof ConsumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ConsumoRoute: ConsumoRoute,
  FacturasRoute: FacturasRoute,
  GastosRoute: GastosRoute,
  InformesRoute: InformesRoute,
  InventarioRoute: InventarioRoute,
  MaterialRoute: MaterialRoute,
  PacientesRoute: PacientesRoute,
  PerfilesRoute: PerfilesRoute,
  RecordatoriosRoute: RecordatoriosRoute,
  UsuariosRoute: UsuariosRoute,
  VisitasRoute: VisitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
