/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitasRouteImport } from './routes/visitas'
import { Route as PerfilesRouteImport } from './routes/perfiles'
import { Route as MaterialRouteImport } from './routes/material'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as IndexRouteImport } from './routes/index'

const VisitasRoute = VisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilesRoute = PerfilesRouteImport.update({
  id: '/perfiles',
  path: '/perfiles',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRoute = MaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/material': typeof MaterialRoute
  '/perfiles': typeof PerfilesRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/material': typeof MaterialRoute
  '/perfiles': typeof PerfilesRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gastos': typeof GastosRoute
  '/material': typeof MaterialRoute
  '/perfiles': typeof PerfilesRoute
  '/visitas': typeof VisitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gastos' | '/material' | '/perfiles' | '/visitas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gastos' | '/material' | '/perfiles' | '/visitas'
  id: '__root__' | '/' | '/gastos' | '/material' | '/perfiles' | '/visitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GastosRoute: typeof GastosRoute
  MaterialRoute: typeof MaterialRoute
  PerfilesRoute: typeof PerfilesRoute
  VisitasRoute: typeof VisitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitas': {
      id: '/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof VisitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfiles': {
      id: '/perfiles'
      path: '/perfiles'
      fullPath: '/perfiles'
      preLoaderRoute: typeof PerfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material': {
      id: '/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof MaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GastosRoute: GastosRoute,
  MaterialRoute: MaterialRoute,
  PerfilesRoute: PerfilesRoute,
  VisitasRoute: VisitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
